# Generated by Django 5.1.6 on 2025-02-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'word_category',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('english_version', models.CharField(max_length=255)),
                ('word_translation', models.CharField(max_length=255)),
                ('modified_datetime', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='api.wordcategory')),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
