# Generated by Django 5.1.6 on 2025-02-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='modified_datetime',
        ),
        migrations.RemoveField(
            model_name='wordcategory',
            name='modified_datetime',
        ),
    ]
