# Generated by Django 5.1.6 on 2025-03-06 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'letters',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('letter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='api.letters')),
            ],
            options={
                'db_table': 'letters_example',
            },
        ),
    ]
