# Generated by Django 5.1.6 on 2025-03-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_letter_id_example_letter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='example_text',
            new_name='example',
        ),
    ]
